#!/usr/bin/env python3
"""Persistent local audio worker used by the Ollama WebSocket proxy.

Protocol: newline-delimited JSON on stdin/stdout.  ``{"audio": "base64"}``
accepts a complete WebM/Opus recording and returns a transcript. ``{"tts":
"text"}`` returns a base64 WAV generated by Piper when a model is installed.
The worker stays alive so faster-whisper is loaded only once per dev server.
"""
import base64, json, os, subprocess, sys, tempfile, wave

try:
    from faster_whisper import WhisperModel
except Exception:
    WhisperModel = None
try:
    from silero_vad import load_silero_vad, get_speech_timestamps, read_audio
    vad_model = load_silero_vad()
except Exception:
    vad_model = None

MODEL = os.getenv("WHISPER_MODEL", "small")
LANGUAGE = os.getenv("WHISPER_LANGUAGE", "auto")
whisper = None
if WhisperModel is not None:
    try:
        whisper = WhisperModel(MODEL, device="cuda" if os.getenv("CUDA_VISIBLE_DEVICES", "") not in ("", "-1") else "cpu", compute_type="float16" if os.getenv("CUDA_VISIBLE_DEVICES", "") not in ("", "-1") else "int8")
    except Exception:
        whisper = None

def emit(value):
    sys.stdout.write(json.dumps(value, ensure_ascii=False) + "\n")
    sys.stdout.flush()

def transcribe(raw):
    with tempfile.TemporaryDirectory(prefix="gev-audio-") as directory:
        source = os.path.join(directory, "input.webm")
        wav = os.path.join(directory, "input.wav")
        open(source, "wb").write(raw)
        converted = subprocess.run(["ffmpeg", "-loglevel", "error", "-y", "-i", source, "-ar", "16000", "-ac", "1", wav], capture_output=True)
        if converted.returncode != 0 or whisper is None:
            return ""
        if vad_model is not None:
            try:
                if not get_speech_timestamps(read_audio(wav, sampling_rate=16000), vad_model): return ""
            except Exception:
                pass
        segments, _ = whisper.transcribe(
            wav,
            language=None if LANGUAGE == "auto" else LANGUAGE,
            vad_filter=True,
            beam_size=5,
            condition_on_previous_text=False,
            initial_prompt="Commande de navigation du globe : va à Paris, Londres, Tokyo, Austin, New York, San Francisco, Dubaï, Tallinn ou Washington DC.",
        )
        return " ".join(segment.text.strip() for segment in segments).strip()

def synthesize(text):
    model = os.getenv("PIPER_MODEL", "")
    if not model or not os.path.exists(model):
        return None
    with tempfile.TemporaryDirectory(prefix="gev-tts-") as directory:
        output = os.path.join(directory, "speech.wav")
        piper = os.path.join(os.path.dirname(sys.executable), "piper")
        command = [piper, "--model", model, "--output_file", output] if os.path.exists(piper) else [sys.executable, "-m", "piper", "--model", model, "--output_file", output]
        process = subprocess.run(command, input=text.encode(), capture_output=True)
        if process.returncode != 0 or not os.path.exists(output): return None
        return base64.b64encode(open(output, "rb").read()).decode()

for line in sys.stdin:
    try:
        event = json.loads(line)
        if "audio" in event:
            emit({"type": "transcript", "text": transcribe(base64.b64decode(event["audio"]))})
        elif "tts" in event:
            emit({"type": "audio", "audio": synthesize(str(event["tts"]))})
    except Exception as error:
        emit({"type": "error", "error": str(error)})
